spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/policy_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update   # change from validate

  flyway:
    enabled: true      # disable for now